---
imports: (( &temporary ))
landscape: (( &temporary ))

settings:
  certificate:
    name: dashboard-identity-ingress
    domains:
      - (( "*." imports.ingress-controller.export.ingress_domain ))
      - (( .landscape.dashboard.cname.domain || ~~ ))
    secret_name: identity-dashboard-tls
    namespace: (( .landscape.namespace ))

plugins:
  - kubectl: cert
  - -echo: "The export generation waits for the certificate, which may take some time."

cert:
  kubeconfig: (( .landscape.clusters[0].kubeconfig ))
  manifests:
    - apiVersion: cert.gardener.cloud/v1alpha1
      kind: Certificate
      metadata:
        name: (( .settings.certificate.name ))
        namespace: (( .settings.certificate.namespace ))
        annotations:
          cert.gardener.cloud/class: (( .imports.dns-controller.export.dns-class ))
      spec:
        secretName: (( .settings.certificate.secret_name ))
        commonName: (( .settings.certificate.domains[0] ))
        dnsNames: (( .settings.certificate.domains[1..] ))
        issuerRef:
          name: (( imports.cert-controller.export.issuerName ))
